# name -> (stage, display label, tooltip)   stages: 0 wrapper,1 clean,2 colour,3 light,4 detail,5 finish,X no-depth/dead,F fun/special
D={}
def a(st,name,label,tip): D[name]=(st,label,tip)
DEAD="Needs a depth buffer. This engine does not provide a usable one, so expect little or no effect, and it can cost frames. Leave it off."
# 0
a('0','UI_Before','UI Before','Always the FIRST effect in a chain. Hides the sidebar from everything below it so only the playfield is graded. Pair with UI Before/After and set Isolate_UI=1.')
a('0','UI_After','UI After','Always the LAST effect in a chain. Puts the sidebar back untouched after all the effects above it.')
a('0','UIDetect','UI Detect','Alternative UI helper from another setup. The presets use UI Before/UI After instead.')
a('0','UIDetect_Before','UI Detect Before','Alternative UI helper from another setup. Use UI Before instead.')
a('0','UIDetect_After','UI Detect After','Alternative UI helper from another setup. Use UI After instead.')
a('0','UIMask_Top','UI Mask Top','Alternative UI helper from another setup. Use UI Before/UI After instead.')
a('0','UIMask_Bottom','UI Mask Bottom','Alternative UI helper from another setup. Use UI Before/UI After instead.')
# 1 clean-up
a('1','FXAA','FXAA','Fast edge smoothing. Slightly softens sprite edges. Use one anti-aliasing effect, not two.\nGoes at the very start of the chain.')
a('1','SMAA','SMAA','Sharper edge smoothing than FXAA but heavier. Use one anti-aliasing effect, not two.\nGoes at the start of the chain.')
a('1','Deband','Deband','Smooths colour banding in gradients (sky, fog, glow). Cheap and safe.\nGoes near the start of the chain, before colour work.')
a('1','KNearestNeighbors','Denoise KNN','Removes noise while keeping edges. Softens fine detail, so rarely needed here.\nGoes at the start of the chain.')
a('1','NonLocalMeans','Denoise NLM','Stronger, slower noise removal. Softens fine detail, so rarely needed here.\nGoes at the start of the chain.')
a('1','SurfaceBlur','Surface Blur','Blurs flat areas but keeps edges. A strong soft look, use sparingly.\nGoes at the start of the chain.')
a('1','GaussianBlur','Gaussian Blur','Plain blur over the whole picture. Mostly useful as a building block or a dream look.\nGoes at the start of the chain.')
a('2','TriDither','Tri Dither','Adds tiny noise to hide banding after heavy colour work.\nGoes last among the colour effects.')
# 2 colour
a('2','LUT','LUT','Applies a full colour grade from a lookup image (set with fLUT_TextureName). The backbone of the custom presets.\nGoes after clean-up, before bloom.')
a('2','MultiLUT','Multi LUT','Colour grade from a set of built-in lookup images to pick from.\nGoes after clean-up, before bloom.')
a('2','Curves','Curves','Adds or removes contrast with an S-curve. Gentle values only.\nGoes in the colour stage.')
a('2','Levels','Levels','Sets black point and white point. Fixes washed-out or crushed images.\nGoes in the colour stage.')
a('2','LevelsPlus','Levels Plus','Advanced levels with per-channel control and gamma.\nGoes in the colour stage.')
a('2','LiftGammaGain','Lift Gamma Gain','Colour balance for shadows, midtones and highlights. Fine control, needs a careful hand.\nGoes in the colour stage.')
a('2','Vibrance','Vibrance','Boosts the colours that are least saturated. Kinder than a plain saturation boost.\nGoes in the colour stage.')
a('2','Colourfulness','Colourfulness','Boosts saturation across the picture. Easy to overdo on tiberium.\nGoes in the colour stage.')
a('2','Tint','Tint (Sepia)','Washes the picture toward one colour. Strong, so use low values.\nGoes in the colour stage.')
a('2','Technicolor','Technicolor','Old-film colour look. Pushes reds and greens hard.\nGoes in the colour stage. Counts as a tone effect.')
a('2','Technicolor2','Technicolor 2','Second old-film colour look, subtler than Technicolor.\nGoes in the colour stage. Counts as a tone effect.')
a('2','DPX','DPX','Cinema-film look: warm and contrasty. A tone curve.\nGoes in the colour stage. Counts as a tone effect.')
a('2','FilmicPass','Filmic Pass','Filmic tone curve with a colour cast.\nGoes in the colour stage. Counts as a tone effect.')
a('2','HDR','Fake HDR','Fake high-dynamic-range look. Gritty and heavy, easy to overcook.\nGoes in the colour stage. Counts as a tone effect.')
a('2','Tonemap','Tonemap','Exposure, gamma and saturation controls. A plain tone curve.\nGoes in the colour stage. Counts as a tone effect.')
a('2','EyeAdaption','Eye Adaption','Slowly brightens or darkens as the scene changes. Can pump on a static camera.\nGoes in the colour stage.')
a('2','Monochrome','Monochrome','Black and white with adjustable filter colours. The GDI-feed look.\nGoes in the colour stage.')
a('2','HSLShift','HSL Shift','Shifts hue, saturation and lightness for chosen colour ranges. Advanced.\nGoes in the colour stage.')
a('2','ColorMatrix','Color Matrix','Remixes the colour channels with a matrix. Advanced.\nGoes in the colour stage.')
a('2','Daltonize','Daltonize','Colour-blind assist mode. Not a look effect.\nGoes in the colour stage.')
a('2','prod80_01A_RT_Correct_Contrast','PD80 Correct Contrast','Automatically adjusts black and white points to fix contrast. Subtle correction tool.\nGoes at the start of the colour stage.')
a('2','prod80_01B_RT_Correct_Color','PD80 Correct Color','Removes colour casts and tints automatically. Subtle correction tool.\nGoes at the start of the colour stage.')
a('2','prod80_04_ContrastBrightnessSaturation','PD80 Contrast Bright Sat','Contrast, brightness and saturation with clean controls.\nGoes in the colour stage.')
a('2','MCAmber','MC Amber','Amber monochrome monitor tint.\nGoes in the colour stage.')
a('2','MCGreen','MC Green','Green monochrome monitor tint.\nGoes in the colour stage.')
a('2','MCOrange','MC Orange','Orange monochrome monitor tint.\nGoes in the colour stage.')
a('2','Nightvision','Night Vision','Green night-vision goggle look.\nGoes in the colour stage.')
# 3 light
a('3','AmbientLight','Ambient Light','Adds a soft light wash spread from the bright areas. Sets the mood. Keep AL_Lens off. AL_Dirt makes the glow, so leave it on, and keep AL_DirtTex off.\nGoes after colour, with the bloom.')
a('3','MagicBloom','Magic Bloom','Strong bloom with adaptive exposure. Threshold and intensity matter most.\nGoes in the light stage. Use one main bloom.')
a('3','Bloom','Bloom (qUINT)','Clean, gentle bloom.\nGoes in the light stage. Use one main bloom.')
a('3','PPFXBloom','PPFX Bloom','Bloom from the PPFX pack.\nGoes in the light stage. Use one main bloom.')
a('3','Pirate_Bloom','Pirate Bloom','Bloom with its own tint controls. Found in older presets.\nGoes in the light stage. Use one main bloom.')
a('3','prod80_02_Bloom','PD80 Bloom','Bloom with colour-temperature tint: cold (about 11000K) for ion storms, warm (about 2400K) for fire.\nGoes in the light stage. Best as a tinted glow on top of one main bloom.')
a('3','BloomAndLensFlares','Bloom + Lens Flares','Bloom plus lens flares, godrays and dirt. The plain bloom works. The flare, godray and lens features look wrong in this engine, so keep them off.\nGoes in the light stage.')
a('3','HeatHaze','Heat Haze','Wobbling heat-shimmer distortion. Good for fire and desert looks.\nGoes in the light stage.')
a('3','MotionBlur','Motion Blur','Smears frames together. Looks smeary in a top-down strategy game. Usually leave off.\nGoes in the light stage.')
a('3','ReflectiveBumpmapping','Reflective Bump Mapping','Adds shiny reflective highlights from image brightness. Partly works here but reads flat surfaces oddly, so judge it by eye.\nGoes in the light stage.')
# 4 detail
a('4','Clarity','Clarity','Adds local contrast to midtones. Makes sprites pop without harsh edges.\nGoes in the detail stage, after bloom.')
a('4','LumaSharpen','Luma Sharpen','Sharpens using brightness only. The safe default sharpener. Use one sharpener.\nGoes in the detail stage, after bloom.')
a('4','DELC_Sharpen','Sharpen (qUINT)','Adjustable sharpener for texture detail. Use one sharpener.\nGoes in the detail stage, after bloom.')
a('4','HighPassSharp','High Pass Sharpen','Overlay-style sharpening. Strong and easy to overdo. Use one sharpener.\nGoes in the detail stage, after bloom.')
a('4','AdaptiveSharpen','Adaptive Sharpen','Sharpens edges more than flat areas, which reduces halos. Use one sharpener.\nGoes in the detail stage, after bloom.')
a('4','Mode1','FineSharp Mode 1','Fine multi-pass sharpening, mode 1 of 3. Heavy. Use one FineSharp mode only.\nGoes in the detail stage, after bloom.')
a('4','Mode2','FineSharp Mode 2','Fine multi-pass sharpening, mode 2 of 3. Heavy. Use one FineSharp mode only.\nGoes in the detail stage, after bloom.')
a('4','Mode3','FineSharp Mode 3','Fine multi-pass sharpening, mode 3 of 3. Heavy. Use one FineSharp mode only.\nGoes in the detail stage, after bloom.')
a('4','FilmicAnamorphSharpen','Filmic Anamorphic Sharpen','Film-style sharpening with a softer character. Use one sharpener.\nGoes in the detail stage, after bloom.')
# 5 finish
a('5','Vignette','Vignette','Darkens the screen edges. Centre it on the playfield (Center=0.395,0.518) so the sidebar does not skew it.\nGoes near the end of the chain.')
a('5','FilmGrain','Film Grain','Adds film noise. Keep it low. Should be the last visible effect.\nGoes at the end of the chain, before UI After.')
a('5','FilmGrain2','Film Grain 2','Second film-noise style. Keep it low. Should be the last visible effect.\nGoes at the end of the chain, before UI After.')
a('5','CA','Chromatic Aberration','Splits colour fringes toward the edges like a cheap lens. Subtle only.\nGoes in the finish stage.')
a('5','ChromaticAberration','Chromatic Aberration (Prism)','Prism-style colour fringing. Subtle only.\nGoes in the finish stage.')
a('5','ScanlinesAbs','Scanlines','Horizontal scanlines for the tactical-feed look.\nGoes in the finish stage.')
for n,l,t in [('AdvancedCRT','CRT Advanced','Tube-monitor emulation with many options.'),('ApertureCRT','CRT Aperture','Aperture-grille tube emulation.'),('CRTCaligari','CRT Caligari','Soft phosphor-glow tube emulation.'),('EasymodeCRT','CRT Easymode','Simple tube emulation with scanlines.'),('GeomCRT','CRT Geom','Curved-screen tube emulation.'),('CRTHyllian','CRT Hyllian','Tube emulation with strong scanline shaping. Used by the Retro preset.'),('LottesCRT','CRT Lottes','Popular tube emulation with mask and bloom.'),('cgwgCRT','CRT cgwg','Classic tube emulation.'),('GTUV50','CRT GTU','Signal-blur tube emulation.'),('CRT_NES_MINI','CRT NES Mini','Small console-style tube look.')]:
    a('5',n,l,t+' Heavy look. Use one CRT effect only.\nGoes in the finish stage.')
a('5','Border','Border','Draws a border around the picture. Novelty.\nGoes in the finish stage.')
a('5','Nostalgia','Nostalgia','Retro colour and pixel look. Novelty.\nGoes in the finish stage.')
a('5','EGAfilter','EGA Filter','Limits colours to the old EGA palette. Novelty.\nGoes in the finish stage.')
a('5','HQ4X','HQ4X','Pixel-art upscaler look. Novelty.\nGoes in the finish stage.')
a('5','LeiFx_Tech','LeiFx 3DFX','Voodoo-era 3D card look with dithering. Novelty.\nGoes in the finish stage.')
a('5','Resolutionizer','Resolutionizer','Fakes a lower resolution. Novelty. The game already runs at 800x600.\nGoes in the finish stage.')
a('5','NTSC_RetroArch','NTSC RetroArch','Analogue TV colour bleed emulation. Novelty.\nGoes in the finish stage.')
a('5','NTSC_MAME','NTSC MAME','Analogue TV colour bleed emulation. Novelty.\nGoes in the finish stage.')
a('5','PAL','PAL','PAL TV emulation. Novelty.\nGoes in the finish stage.')
a('5','PAL_R57','PAL R57','PAL TV emulation, second version. Novelty.\nGoes in the finish stage.')
# F special-purpose
for n,l,t in [('ASCII','ASCII','Draws the picture as text characters. Novelty.'),('Cartoon','Cartoon','Cartoon outline look. Novelty.'),('GlitchB','Glitch','Digital glitch distortion. Novelty.'),('Layer','Layer','Overlays an image. Special purpose.'),('AspectRatioPS','Aspect Ratio','Corrects image aspect ratio. Not needed at 800x600.'),('PerfectPerspective','Perfect Perspective','Corrects lens distortion (fish-eye, panini). Not needed here.'),('Before','Splitscreen Before','Helper pair for a split-screen comparison. Special purpose.'),('After','Splitscreen After','Helper pair for a split-screen comparison. Special purpose.'),('TiltShift','Tilt Shift','Blurs the top and bottom for a miniature look. Works without depth, but blurs part of the playfield.')]:
    a('6',n,l,t+'\nSkip for normal play.')
# X dead
for n,l,t in [('MXAO','MXAO','Ambient occlusion shadows.'),('PPFXSSDO','PPFX SSDO','Directional occlusion and indirect light.'),('LightDoF_Near','Light DoF Near','Near-field depth of field.'),('LightDoF_Far','Light DoF Far','Far-field depth of field.'),('LightDoF_AutoFocus','Light DoF Auto Focus','Auto-focus depth of field.'),('CinematicDOF','Cinematic DOF','Cinematic depth of field.'),('RingDOF','Ring DOF','Ring-style depth of field.'),('MagicDOF','Magic DOF','Depth of field.'),('GP65CJ042DOF','GP65CJ042 DOF','Depth of field.'),('MatsoDOF','Matso DOF','Depth of field.'),('MartyMcFlyDOF','MartyMcFly DOF','Depth of field.'),('DepthHaze','Depth Haze','Fog that builds with distance.'),('AdaptiveFog','Adaptive Fog','Distance fog.'),('Emphasize','Emphasize','Colours by distance.'),('Depth3D','Depth3D','Stereoscopic 3D from depth.'),('Chromakey','Chromakey','Green screen from depth.'),('StageDepth','Stage Depth','Depth-based stage effect.'),('DisplayDepth','Display Depth','Diagnostic view of the depth buffer.'),('PPFX_Godrays','PPFX Godrays','Light rays from bright areas. Looks wrong in this engine.')]:
    a('X',n,l,t+' '+DEAD)
